Fix an N^2 in batch hydration
camsaul/toucan2 pull request #172
Opened 2024-07-31 02:16 UTC by bshepherdson

This hadn't been noticed previously since N is generally small, eg. 50 or 60 at most. Working with a Metabase dashboard that loaded 10000 fields (100 each from 100 tables) in a single `select` + `hydrate`, I found this was consuming about 3 seconds.

The slow path was effectively a very slow `conj`: taking the `acc` vector, and then for each `annotated-instances` doing:

```clojure
(recur (vec (concat acc nil [(first hydrated-instances)]))
       ...)
```

which is pouring the whole vector into a lazy sequence and back into a vector, once for each instance in the list.

The new version uses a custom transducer to do the same process in O(n) time (and without any seq overhead, as a bonus).

2024-07-31 17:29 UTC, alexander-yakushev commented on src/toucan2/tools/hydrate.clj
> +      (fn
Can rewrite this to use `completing` if you don't need custom 0- and 1-arity.

2024-08-14 22:53 UTC, camsaul approved these changes

2024-08-14 22:54 UTC, camsaul requested changes
Can you update the failing tests?

2024-09-12 20:36 UTC, alexander-yakushev commented
Bump. I've rewritten the implementation of merging original instances with batch-hydrated instances again. I'm building an index that serves both as the indicator which instances should be taken into the batch to be hydrated and which not; and also it enumerates the instances-to-by-hydrates, so that on the second pass of this index, we can extract the hydrated instances by their position in the batch.

The tests are now fixes.

2024-12-18 18:11 UTC, camsaul approved these changes

2024-12-18 18:11 UTC, merged