[select] Use transients in select-reducing functions
camsaul/toucan2 pull request #186
Opened 2024-10-05 09:46 UTC by alexander-yakushev

According to my benchmarks, using transients here yields allocation advantage and some runtime boost as well. I'm not sure about the name of the new function, maybe it should be `with-transient-conj!-init` or something like that?

2024-10-07 19:30 UTC, camsaul commented on src/toucan2/jdbc/mysql_mariadb.clj
> +        select-rf      (pipeline/conj!-with-init [])
I'd rather call it `conj-with-init!` or something -- having it end in an `!` makes it clearer that this is a thread-unsafe/STM-unsafe function and we have some custom linters in MB core that actually do smart things with symbols named this way

2024-10-07 19:32 UTC, camsaul requested changes
Overall this looks good but can we rename the function to `conj-with-init!`, then I'll go ahead and approve and merge this

2024-10-08 07:05 UTC, alexander-yakushev commented
Done

2024-12-11 21:46 UTC, alexander-yakushev commented
Bump:) Is there anything else that you'd like to change here?

2024-12-18 18:11 UTC, camsaul approved these changes

2024-12-18 18:11 UTC, merged