Fix a footgun in `before-update`
camsaul/toucan2 pull request #196
Opened 2024-11-21 22:13 UTC by johnswanson

If the `before-update` method returned an object without a primary key, we would emit a bad `UPDATE` without any where clause.

(I'd be happy to add some tests tomorrow, I need to head out today though.)

2024-11-22 17:36 UTC, camsaul commented on src/toucan2/tools/before_update.clj
> +           row          (before-update model row)
Don't we still want to be doing this??

```suggestion
           row          (merge realized-row changes)
           row          (before-update model realized-row)
```

2024-11-22 17:37 UTC, camsaul commented on src/toucan2/tools/before_update.clj
> +           row          (merge row changes)
Don't we still want to be merging `changes` into the `realized-row`?

```suggestion
           row          (merge realized-row changes)
```

2024-11-22 17:40 UTC, camsaul requested changes
This seems like it's changing a lot of behavior, the old code realized the row and then used that as `row` everywhere, the new code keeps `realized-row` separately but doesn't thread that thru to everything else like it did before.

It probably doesn't make a difference since under the hood the underlying transient `Row` object should know it was already realized elsewhere and return the realized version but I think by making the change I suggested it would make the code a little clearer and eliminate a little bit of overhead

2024-11-25 12:55 UTC, johnswanson commented
> This seems like it's changing a lot of behavior, the old code realized the row and then used that as row everywhere, the new code keeps realized-row separately but doesn't thread that thru to everything else like it did before.

> It probably doesn't make a difference since under the hood the underlying transient Row object should know it was already realized elsewhere and return the realized version but I think by making the change I suggested it would make the code a little clearer and eliminate a little bit of overhead

Doh, yeah - sorry about that!

2024-11-26 14:31 UTC, johnswanson commented
@camsaul it looks like MariaDB has changed the error format from

```
Unknown column 'venue_name' in 'SET'
```

vs 

```
Unknown column 'venue_name' in 'field list'
```

in the test case between 11.3 and 11.4 - locally things pass if I run `mariadb:11.3` but fail if I run `mariadb:11.4`. Just pushed a commit that should fix that.

2024-11-26 21:27 UTC, merged